package:
  name: "reliontomotools"
  version: "0.0.3"

source:
  git_rev: v0.0.2
  git_url: https://github.com/joton/reliontomotools

build:
    script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  host:
    - python
    - setuptools

  run:
    - python
    - numpy>=1.19
    - pandas
    - xmltodict
    - docopt
    - scipy
    - tqdm
    - mrcfile


about:
  home: https://github.com/joton/reliontomotools
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Additional tools for Relion tomo"
